name: test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"   # à¹ƒà¸Šà¹‰à¹ƒà¸«à¹‰à¹€à¸‚à¹‰à¸²à¸à¸±à¸š Flutter 3.24.x (Dart 3.5.x)

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # Networking / Storage
  http: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3

  # Firebase/Backend & Auth
  supabase_flutter: ^2.10.0
  sign_in_with_apple: ^7.0.1   # à¹ƒà¸Šà¹‰à¸šà¸™ iOS/macOS à¹€à¸—à¹ˆà¸²à¸™à¸±à¹‰à¸™

  # Utils
  uuid: ^4.5.0
  csv: ^6.0.0

  # UI Widgets
  table_calendar: ^3.0.9
  fl_chart: ^0.70.2           # à¹ƒà¸Šà¹‰à¹à¸—à¸™ charts_flutter
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Splash & App Icon
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/S11_clean.csv
    - assets/here.png        # ðŸ‘ˆ à¹„à¸Ÿà¸¥à¹Œà¹‚à¸¥à¹‚à¸à¹‰à¸«à¸±à¸§à¹ƒà¸ˆà¸ªà¸µà¹€à¸‚à¸µà¸¢à¸§ HereMe
    - assets/c.png
    - assets/hereme.png
  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
        - asset: assets/fonts/NotoSansThai-Bold.ttf
        - asset: "assets/fonts/NotoSansThai-VariableFont_wdth,wght.ttf"
          weight: 700

# ðŸ‘‡ Native splash (à¸à¹ˆà¸­à¸™à¹€à¸Ÿà¸£à¸¡à¹à¸£à¸)
flutter_native_splash:
  color: "#ffffff"          # à¸ªà¸µà¸žà¸·à¹‰à¸™à¸«à¸¥à¸±à¸‡
  image: assets/c.png     # 1x1 à¹‚à¸›à¸£à¹ˆà¸‡à¹ƒà¸ª
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: assets/c.png   # 1x1 à¹‚à¸›à¸£à¹ˆà¸‡à¹ƒà¸ª (à¹à¸à¹‰à¸›à¸±à¸à¸«à¸²à¹„à¸­à¸„à¸­à¸™à¸§à¸‡à¸à¸¥à¸¡)


# ðŸ‘‡ App icon
flutter_icons:
  android: true
  ios: true
  image_path: assets/here.png   # à¹à¸™à¸°à¸™à¸³à¹„à¸Ÿà¸¥à¹Œ PNG 1024x1024
  remove_alpha_ios: true
